# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ${BASE_IMAGE}

RUN apt-get install -y gcp-php56-amqp \
                       gcp-php56-apm \
                       gcp-php56-eio \
                       gcp-php56-hprose \
                       gcp-php56-jsond \
                       gcp-php56-krb5 \
                       gcp-php56-libsodium \
                       gcp-php56-lzf \
                       gcp-php56-memprof \
                       gcp-php56-seaslog \
                       gcp-php56-stomp \
                       gcp-php56-swoole \
                       gcp-php56-sync \
                       gcp-php56-tcpwrap \
                       gcp-php56-timezonedb \
                       gcp-php56-yaf \
                       gcp-php56-yaml \
                       gcp-php56-zip
