# TODO: fix app names

steps:
  # test runner
  - name: gcr.io/cloud-builders/docker
    args: ['pull', '$_TEST_RUNNER']
    waitFor: ['-']
    id: test-runner

  # test network for making local docker http requests
  - name: gcr.io/cloud-builders/docker
    args: ['network', 'create', '-d', 'bridge', 'nw_$_TAG']
    waitFor: ['-']
    id: test-network

  # php-default test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php-default:$_TAG', '.']
    dir: php_default
    waitFor: ['-']
    id: php-default-build
  - name: gcr.io/gcp-runtimes/structure_test
    args: ['-i', 'gcr.io/$PROJECT_ID/php-default:$_TAG', '--config', 'php_default.yaml', '-v']
    waitFor: ['php-default-build']

  # php56 test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php56:$_TAG', '.']
    dir: php56
    waitFor: ['-']
    id: php56-build
  - name: gcr.io/gcp-runtimes/structure_test
    args: ['-i', 'gcr.io/$PROJECT_ID/php56:$_TAG', '--config', 'php56.yaml', '-v']
    waitFor: ['php56-build']
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '--name=php56', '-d', 'gcr.io/$PROJECT_ID/php56:$_TAG']
    waitFor: ['php56-build', 'test-network']
    id: php56-app
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/php-test-runner:$_TAG', '/workspace/php56']
    waitFor: ['php56-app', 'test-runner']

  # php56-custom test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php56-custom:$_TAG', '.']
    dir: php56_custom
    waitFor: ['-']
    id: php56-custom-build
  - name: gcr.io/gcp-runtimes/structure_test
    args: ['-i', 'gcr.io/$PROJECT_ID/php56-custom:$_TAG', '--config', 'php56_custom.yaml', '-v']
    waitFor: ['php56-custom-build']
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '--name=php56-custom', '-d', 'gcr.io/$PROJECT_ID/php56-custom:$_TAG']
    waitFor: ['php56-custom-build', 'test-network']
    id: php56-custom-app
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG','-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/php-test-runner:$_TAG', '/workspace/php56_custom']
    waitFor: ['php56-custom-app', 'test-runner']

  # php56-custom-configs test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php56-custom-configs:$_TAG', '.']
    dir: php56_custom_configs
    waitFor: ['-']
    id: php56-custom-configs-build
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '--name=php56-custom-configs', '-d', 'gcr.io/$PROJECT_ID/php56-custom-configs:$_TAG']
    waitFor: ['php56-custom-configs-build', 'test-network']
    id: php56-custom-configs-app
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/php-test-runner:$_TAG', '/workspace/php56_custom_configs']
    waitFor: ['php56-custom-configs-app', 'test-runner']

  # php56-extensions test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php56-extensions:$_TAG', '.']
    dir: php56_extensions
    waitFor: ['-']
    id: php56-extensions-build
  - name: gcr.io/cloud-builders/docker
    args: ['run', 'gcr.io/$PROJECT_ID/php56-extensions:$_TAG', 'vendor/bin/phpunit']
    dir: php56_extensions
    waitFor: ['php56-extensions-build']

  # php56-nginx-conf test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php56-nginx-conf:$_TAG', '.']
    dir: php56_nginx_conf
    waitFor: ['-']
    id: php56-nginx-conf-build
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '--name=php56-nginx-conf', '-d', 'gcr.io/$PROJECT_ID/php56-nginx-conf:$_TAG']
    waitFor: ['php56-nginx-conf-build', 'test-network']
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/php-test-runner:$_TAG', '/workspace/php56_nginx_conf']
    waitFor: ['php56-nginx-conf-build', 'test-runner']

  # php70-custom test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php70-custom:$_TAG', '.']
    dir: php70_custom
    waitFor: ['-']
    id: php70-custom-build
  - name: gcr.io/gcp-runtimes/structure_test
    args: ['-i', 'gcr.io/$PROJECT_ID/php70-custom:$_TAG', '--config', 'php70.yaml', '-v']
    waitFor: ['php70-custom-build']
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '--name=php70-custom', '-d', 'gcr.io/$PROJECT_ID/php70-custom:$_TAG']
    waitFor: ['php70-custom-build', 'test-network']
    id: php70-custom-app
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG','-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/php-test-runner:$_TAG', '/workspace/php70_custom/tests']
    waitFor: ['php70-custom-app', 'test-runner']

  # php70-extensions test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php70-extensions:$_TAG', '.']
    dir: php70_extensions
    waitFor: ['-']
    id: php70-extensions-build
  - name: gcr.io/cloud-builders/docker
    args: ['run', 'gcr.io/$PROJECT_ID/php70-extensions:$_TAG', 'vendor/bin/phpunit']
    dir: php70_extensions
    waitFor: ['php70-extensions-build']

  # php71-custom test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php71-custom:$_TAG', '.']
    dir: php71_custom
    waitFor: ['-']
    id: php71-custom-build
  - name: gcr.io/gcp-runtimes/structure_test
    args: ['-i', 'gcr.io/$PROJECT_ID/php71-custom:$_TAG', '--config', 'php71.yaml', '-v']
    waitFor: ['php71-custom-build']
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG', '--name=php71-custom', '-d', 'gcr.io/$PROJECT_ID/php71-custom:$_TAG']
    waitFor: ['php71-custom-build', 'test-network']
    id: php71-custom-app
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--net=nw_$_TAG','-v', '/workspace:/workspace', 'gcr.io/$PROJECT_ID/php-test-runner:$_TAG', '/workspace/php71_custom/tests']
    waitFor: ['php71-custom-app', 'test-runner']

  # php71-extensions test
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/php71-extensions:$_TAG', '.']
    dir: php71_extensions
    waitFor: ['-']
    id: php71-extensions-build
  - name: gcr.io/cloud-builders/docker
    args: ['run', 'gcr.io/$PROJECT_ID/php71-extensions:$_TAG', 'vendor/bin/phpunit']
    dir: php71_extensions
    waitFor: ['php71-extensions-build']
