# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM ${BASE_IMAGE}

RUN apt-get update && \
    apt-get install -y gcp-php70-amqp \
                       gcp-php70-apm \
                       gcp-php70-couchbase \
                       gcp-php70-ds \
                       gcp-php70-eio \
                       gcp-php70-hprose \
                       gcp-php70-jsond \
                       gcp-php70-krb5 \
                       gcp-php70-lua \
                       gcp-php70-lzf \
                       gcp-php70-memprof \
                       gcp-php70-seaslog \
                       gcp-php70-stomp \
                       gcp-php70-swoole \
                       gcp-php70-sync \
                       gcp-php70-tcpwrap \
                       gcp-php70-timezonedb \
                       gcp-php70-v8js \
                       gcp-php70-vips \
                       gcp-php70-yaconf \
                       gcp-php70-yaf \
                       gcp-php70-yaml
