schemaVersion: "1.0.0"

fileContentTests:
  name: "nginx user conf"
  path: "/etc/nginx/conf.d/nginx-user.conf"
  expectedContents: [".*nginx-user\\.conf.*"]

  name: "nginx conf"
  path: "/opt/nginx/conf/nginx.conf"
  expectedContents: [".*nginx-custom\\.conf.*"]

  name: "php from conf"
  path: "/opt/php/etc/php-fpm-user.conf"
  expectedContents: [".*php-fpm-user\\.conf.*"]

  name: "php ini"
  path: "/opt/php/lib/conf.d/php-user.ini"
  expectedContents: [".*php-user\\.ini.*"]

  name: "supervisord conf"
  path: "/etc/supervisor/conf.d/my-supervisord.conf"
  expectedContents: [".*my-supervisord\\.conf.*", ".*custom-supervisord\\.conf.*"]
