# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dockerfile for PHP 5.6/7.0/7.1 using nginx as the webserver.

FROM ${PHP_BASE_IMAGE}

ARG PHP_VERSION=7.1

RUN /bin/bash /build-scripts/install_php.sh && \
    /bin/bash /build-scripts/install_composer.sh && \
    chgrp www-data /tmp/detect_php_version.php && \
    # Temporary enable the shell for www-data
    # We will disable it in entrypoint.sh
    chsh -s /bin/bash www-data && \
      cd /tmp && \
      su www-data -c "php /usr/local/bin/composer require composer/semver"
