runtime: php
env: flex

runtime_config:
  document_root: web
  whitelist_functions: phpinfo,exec

liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
