<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 1.0
// Source: google/protobuf/empty.proto
//   Date: 2016-03-02 22:35:01

namespace google\protobuf {

  class EmptyObject extends \DrSlump\Protobuf\Message
  {


      /** @var \Closure[] */
    protected static $__extensions = array();

      public static function descriptor()
      {
          $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'google.protobuf.Empty');

          foreach (self::$__extensions as $cb) {
              $descriptor->addField($cb(), true);
          }

          return $descriptor;
      }
  }
}
